/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eunice
 */
public class AdminPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminPanel.class.getName());
    private int appuserPK =0;
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserManagementButton = new javax.swing.JButton();
        ProductManagementButton = new javax.swing.JButton();
        ManageOrderButton = new javax.swing.JButton();
        MenuButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ProductManagement = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        ProductIDtxt = new javax.swing.JLabel();
        ProductID = new javax.swing.JTextField();
        ProductName = new javax.swing.JTextField();
        ProductNameTxt = new javax.swing.JLabel();
        ProductPriceTxt = new javax.swing.JLabel();
        ProductPrice = new javax.swing.JTextField();
        ProductQuantityTxt = new javax.swing.JLabel();
        ProductQuantity = new javax.swing.JTextField();
        ProductCategory = new javax.swing.JComboBox<>();
        ProductCategoryTxt = new javax.swing.JLabel();
        PMsave = new javax.swing.JButton();
        PMupdate = new javax.swing.JButton();
        PMdelete = new javax.swing.JButton();
        UserManagement = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        FirstNameUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LastNameUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EmailUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PhoneUser = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AddressUser = new javax.swing.JTextField();
        UserSave = new javax.swing.JButton();
        UserUpdate = new javax.swing.JButton();
        UserDelete = new javax.swing.JButton();
        ManageOrder = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        OrderID = new javax.swing.JTextField();
        OrderEmail = new javax.swing.JTextField();
        OrderQuantity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        OrderStatus = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        OrderUpdate = new javax.swing.JButton();
        OrderSave = new javax.swing.JButton();
        OrderDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1244, 733));
        setMinimumSize(new java.awt.Dimension(1244, 733));
        setResizable(false);
        setSize(new java.awt.Dimension(1244, 550));

        jPanel1.setBackground(new java.awt.Color(236, 226, 208));
        jPanel1.setMaximumSize(new java.awt.Dimension(1244, 733));
        jPanel1.setMinimumSize(new java.awt.Dimension(1244, 733));
        jPanel1.setPreferredSize(new java.awt.Dimension(1244, 733));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(162, 103, 105));

        jLabel1.setBackground(new java.awt.Color(162, 103, 105));
        jLabel1.setForeground(new java.awt.Color(213, 185, 178));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/LOGO WHITE.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        UserManagementButton.setBackground(new java.awt.Color(162, 103, 105));
        UserManagementButton.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 20)); // NOI18N
        UserManagementButton.setForeground(new java.awt.Color(255, 255, 255));
        UserManagementButton.setText("USER MANAGEMENT");
        UserManagementButton.setBorder(null);
        UserManagementButton.setBorderPainted(false);
        UserManagementButton.setContentAreaFilled(false);
        UserManagementButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UserManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManagementButtonActionPerformed(evt);
            }
        });

        ProductManagementButton.setBackground(new java.awt.Color(162, 103, 105));
        ProductManagementButton.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 20)); // NOI18N
        ProductManagementButton.setForeground(new java.awt.Color(255, 255, 255));
        ProductManagementButton.setText("PRODUCT MANAGEMENT");
        ProductManagementButton.setBorder(null);
        ProductManagementButton.setBorderPainted(false);
        ProductManagementButton.setContentAreaFilled(false);
        ProductManagementButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ProductManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductManagementButtonActionPerformed(evt);
            }
        });

        ManageOrderButton.setBackground(new java.awt.Color(162, 103, 105));
        ManageOrderButton.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 20)); // NOI18N
        ManageOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageOrderButton.setText("MANAGE ORDERS");
        ManageOrderButton.setBorder(null);
        ManageOrderButton.setBorderPainted(false);
        ManageOrderButton.setContentAreaFilled(false);
        ManageOrderButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ManageOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageOrderButtonActionPerformed(evt);
            }
        });

        MenuButton.setBackground(new java.awt.Color(162, 103, 105));
        MenuButton.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 20)); // NOI18N
        MenuButton.setForeground(new java.awt.Color(255, 255, 255));
        MenuButton.setText("MAIN MENU");
        MenuButton.setBorder(null);
        MenuButton.setBorderPainted(false);
        MenuButton.setContentAreaFilled(false);
        MenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });

        LogoutButton.setBackground(new java.awt.Color(162, 103, 105));
        LogoutButton.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 20)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("LOGOUT");
        LogoutButton.setBorder(null);
        LogoutButton.setContentAreaFilled(false);
        LogoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductManagementButton)
                    .addComponent(ManageOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(ManageOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ProductManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(UserManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        jPanel1.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 740));

        ProductManagement.setBackground(new java.awt.Color(213, 185, 178));

        jPanel3.setBackground(new java.awt.Color(213, 185, 178));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(162, 103, 105));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRODUCT MANAGEMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel4.setBackground(new java.awt.Color(213, 185, 178));

        ProductTable.setBackground(new java.awt.Color(213, 185, 178));
        ProductTable.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        ProductTable.setForeground(new java.awt.Color(0, 0, 0));
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "NAME", "PRICE", "QUANTITY", "CATEGORY"
            }
        ));
        ProductTable.setGridColor(new java.awt.Color(0, 0, 0));
        ProductTable.setSelectionBackground(new java.awt.Color(213, 185, 178));
        ProductTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTable);

        ProductIDtxt.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        ProductIDtxt.setForeground(new java.awt.Color(162, 103, 105));
        ProductIDtxt.setText("PRODUCT ID");

        ProductID.setBackground(new java.awt.Color(255, 255, 255));
        ProductID.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        ProductID.setForeground(new java.awt.Color(0, 0, 0));
        ProductID.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        ProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductIDActionPerformed(evt);
            }
        });

        ProductName.setBackground(new java.awt.Color(255, 255, 255));
        ProductName.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        ProductName.setForeground(new java.awt.Color(0, 0, 0));
        ProductName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        ProductNameTxt.setBackground(new java.awt.Color(213, 185, 178));
        ProductNameTxt.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        ProductNameTxt.setForeground(new java.awt.Color(162, 103, 105));
        ProductNameTxt.setText("PRODUCT NAME");

        ProductPriceTxt.setBackground(new java.awt.Color(162, 103, 105));
        ProductPriceTxt.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        ProductPriceTxt.setForeground(new java.awt.Color(162, 103, 105));
        ProductPriceTxt.setText("PRICE");

        ProductPrice.setBackground(new java.awt.Color(255, 255, 255));
        ProductPrice.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        ProductPrice.setForeground(new java.awt.Color(0, 0, 0));
        ProductPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        ProductQuantityTxt.setBackground(new java.awt.Color(162, 103, 105));
        ProductQuantityTxt.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        ProductQuantityTxt.setForeground(new java.awt.Color(162, 103, 105));
        ProductQuantityTxt.setText("QUANTITY");

        ProductQuantity.setBackground(new java.awt.Color(255, 255, 255));
        ProductQuantity.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        ProductQuantity.setForeground(new java.awt.Color(0, 0, 0));
        ProductQuantity.setText("\n");
        ProductQuantity.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        ProductCategory.setBackground(new java.awt.Color(255, 255, 255));
        ProductCategory.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        ProductCategory.setForeground(new java.awt.Color(0, 0, 0));
        ProductCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paper Prints", "Documents", "Merch Prints", "Stationery", "Souvenirs", "Packaging" }));
        ProductCategory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        ProductCategoryTxt.setBackground(new java.awt.Color(162, 103, 105));
        ProductCategoryTxt.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        ProductCategoryTxt.setForeground(new java.awt.Color(162, 103, 105));
        ProductCategoryTxt.setText("CATEGORY");

        PMsave.setBackground(new java.awt.Color(255, 255, 255));
        PMsave.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        PMsave.setForeground(new java.awt.Color(162, 103, 105));
        PMsave.setText("SAVE");
        PMsave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PMsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMsaveActionPerformed(evt);
            }
        });

        PMupdate.setBackground(new java.awt.Color(255, 255, 255));
        PMupdate.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        PMupdate.setForeground(new java.awt.Color(162, 103, 105));
        PMupdate.setText("UPDATE");
        PMupdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PMupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMupdateActionPerformed(evt);
            }
        });

        PMdelete.setBackground(new java.awt.Color(255, 255, 255));
        PMdelete.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        PMdelete.setForeground(new java.awt.Color(162, 103, 105));
        PMdelete.setText("DELETE");
        PMdelete.setBorder(null);
        PMdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductCategoryTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductQuantity)
                            .addComponent(ProductID)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(PMsave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(PMupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(PMdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProductNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductQuantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ProductPrice)
                            .addComponent(ProductName)
                            .addComponent(ProductCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ProductIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProductQuantityTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProductCategoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PMsave, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PMupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PMdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProductManagementLayout = new javax.swing.GroupLayout(ProductManagement);
        ProductManagement.setLayout(ProductManagementLayout);
        ProductManagementLayout.setHorizontalGroup(
            ProductManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProductManagementLayout.setVerticalGroup(
            ProductManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventory", ProductManagement);

        UserManagement.setBackground(new java.awt.Color(213, 185, 178));
        UserManagement.setForeground(new java.awt.Color(162, 103, 105));

        jPanel5.setBackground(new java.awt.Color(213, 185, 178));

        jLabel3.setBackground(new java.awt.Color(162, 103, 105));
        jLabel3.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(162, 103, 105));
        jLabel3.setText("USER MANAGEMENT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(213, 185, 178));

        UserTable.setBackground(new java.awt.Color(213, 185, 178));
        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Email", "Phone", "Address"
            }
        ));
        UserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(UserTable);

        jPanel6.setBackground(new java.awt.Color(213, 185, 178));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(162, 103, 105));
        jLabel5.setText("FIRST NAME");

        FirstNameUser.setBackground(new java.awt.Color(255, 255, 255));
        FirstNameUser.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        FirstNameUser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.lightGray));
        FirstNameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameUserActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(162, 103, 105));
        jLabel6.setText("LAST NAME");

        LastNameUser.setBackground(new java.awt.Color(255, 255, 255));
        LastNameUser.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        LastNameUser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.lightGray));

        jLabel7.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(162, 103, 105));
        jLabel7.setText("EMAIL");

        EmailUser.setBackground(new java.awt.Color(255, 255, 255));
        EmailUser.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        EmailUser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.lightGray));

        jLabel8.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(162, 103, 105));
        jLabel8.setText("PHONE");

        PhoneUser.setBackground(new java.awt.Color(255, 255, 255));
        PhoneUser.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        PhoneUser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.lightGray));

        jLabel9.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(162, 103, 105));
        jLabel9.setText("ADDRESS");

        AddressUser.setBackground(new java.awt.Color(255, 255, 255));
        AddressUser.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        AddressUser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.lightGray));

        UserSave.setBackground(new java.awt.Color(255, 255, 255));
        UserSave.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 12)); // NOI18N
        UserSave.setForeground(new java.awt.Color(162, 103, 105));
        UserSave.setText("SAVE");
        UserSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UserSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSaveActionPerformed(evt);
            }
        });

        UserUpdate.setBackground(new java.awt.Color(255, 255, 255));
        UserUpdate.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 12)); // NOI18N
        UserUpdate.setForeground(new java.awt.Color(162, 103, 105));
        UserUpdate.setText("UPDATE");
        UserUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserUpdateActionPerformed(evt);
            }
        });

        UserDelete.setBackground(new java.awt.Color(255, 255, 255));
        UserDelete.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 12)); // NOI18N
        UserDelete.setForeground(new java.awt.Color(162, 103, 105));
        UserDelete.setText("DELETE");
        UserDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(LastNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(PhoneUser, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(UserSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(UserUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(AddressUser, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailUser))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout UserManagementLayout = new javax.swing.GroupLayout(UserManagement);
        UserManagement.setLayout(UserManagementLayout);
        UserManagementLayout.setHorizontalGroup(
            UserManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserManagementLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserManagementLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        UserManagementLayout.setVerticalGroup(
            UserManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserManagementLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User Management", UserManagement);

        ManageOrder.setBackground(new java.awt.Color(213, 185, 178));

        jPanel7.setBackground(new java.awt.Color(213, 185, 178));

        jLabel4.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(162, 103, 105));
        jLabel4.setText("ORDER MANAGEMENT");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(213, 185, 178));

        jLabel10.setBackground(new java.awt.Color(162, 103, 105));
        jLabel10.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(162, 103, 105));
        jLabel10.setText("ORDER ID");

        jLabel11.setBackground(new java.awt.Color(162, 103, 105));
        jLabel11.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(162, 103, 105));
        jLabel11.setText("EMAIL");

        jLabel12.setBackground(new java.awt.Color(162, 103, 105));
        jLabel12.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(162, 103, 105));
        jLabel12.setText("QUANTITY");

        OrderID.setBackground(new java.awt.Color(255, 255, 255));
        OrderID.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        OrderID.setForeground(new java.awt.Color(0, 0, 0));
        OrderID.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        OrderEmail.setBackground(new java.awt.Color(255, 255, 255));
        OrderEmail.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        OrderEmail.setForeground(new java.awt.Color(0, 0, 0));
        OrderEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        OrderEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderEmailActionPerformed(evt);
            }
        });

        OrderQuantity.setBackground(new java.awt.Color(255, 255, 255));
        OrderQuantity.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        OrderQuantity.setForeground(new java.awt.Color(0, 0, 0));
        OrderQuantity.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel13.setBackground(new java.awt.Color(162, 103, 105));
        jLabel13.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(162, 103, 105));
        jLabel13.setText("STATUS");

        OrderStatus.setBackground(new java.awt.Color(255, 255, 255));
        OrderStatus.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 14)); // NOI18N
        OrderStatus.setForeground(new java.awt.Color(0, 0, 0));
        OrderStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Cancelled", "Completed", "In Progress" }));
        OrderStatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrderEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(31, 31, 31)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrderQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(28, 28, 28)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(213, 185, 178));

        OrderTable.setBackground(new java.awt.Color(213, 185, 178));
        OrderTable.setForeground(new java.awt.Color(0, 0, 0));
        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDER ID", "CUSTOMER NAME", "QUANTITY", "STATUS"
            }
        ));
        OrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(OrderTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        OrderUpdate.setBackground(new java.awt.Color(255, 255, 255));
        OrderUpdate.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        OrderUpdate.setForeground(new java.awt.Color(162, 103, 105));
        OrderUpdate.setText("UPDATE");
        OrderUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        OrderUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderUpdateActionPerformed(evt);
            }
        });

        OrderSave.setBackground(new java.awt.Color(255, 255, 255));
        OrderSave.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        OrderSave.setForeground(new java.awt.Color(162, 103, 105));
        OrderSave.setText("SAVE");
        OrderSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        OrderSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderSaveActionPerformed(evt);
            }
        });

        OrderDelete.setBackground(new java.awt.Color(255, 255, 255));
        OrderDelete.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        OrderDelete.setForeground(new java.awt.Color(162, 103, 105));
        OrderDelete.setText("DELETE");
        OrderDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        OrderDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageOrderLayout = new javax.swing.GroupLayout(ManageOrder);
        ManageOrder.setLayout(ManageOrderLayout);
        ManageOrderLayout.setHorizontalGroup(
            ManageOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ManageOrderLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ManageOrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OrderSave, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(OrderUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(OrderDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        ManageOrderLayout.setVerticalGroup(
            ManageOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ManageOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderSave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manage Order", ManageOrder);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, -42, 940, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrderButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_ManageOrderButtonActionPerformed

    private void UserManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManagementButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_UserManagementButtonActionPerformed

    private void ProductManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductManagementButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_ProductManagementButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void PMsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMsaveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)ProductTable.getModel();
        model.addRow(new Object[]{ProductID.getText(),ProductName.getText(),ProductPrice.getText(),ProductQuantity.getText(),ProductCategory.getSelectedItem()});
        ProductID.setText("");
        ProductName.setText("");
        ProductPrice.setText("");
        ProductQuantity.setText("");
        ProductCategory.setSelectedIndex(0);
    }//GEN-LAST:event_PMsaveActionPerformed

    private void PMdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMdeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)ProductTable.getModel();
        
        try {
            int SelectedRowIndex = ProductTable.getSelectedRow();
            if (SelectedRowIndex >= 0) {
                model.removeRow(SelectedRowIndex);
        
                ProductID.setText("");
                ProductName.setText("");
                ProductPrice.setText("");
                ProductQuantity.setText("");
                ProductCategory.setSelectedIndex(0);
        } else {
                JOptionPane.showMessageDialog(null, "Please select a row to delete");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_PMdeleteActionPerformed

    private void UserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserDeleteActionPerformed
        // TODO add your handling code here:
           DefaultTableModel model =(DefaultTableModel)UserTable.getModel();
        
           try {
                int SelectedRowIndex = UserTable.getSelectedRow();
                if (SelectedRowIndex >= 0) {
                    model.removeRow(SelectedRowIndex);
        
                FirstNameUser.setText("");
                LastNameUser.setText("");
                EmailUser.setText("");
                PhoneUser.setText("");
                AddressUser.setText("");

            JOptionPane.showMessageDialog(null, "User deleted successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a user to delete");
        }
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Error deleting user: " + ex.getMessage());
        }
    }//GEN-LAST:event_UserDeleteActionPerformed

    private void OrderEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderEmailActionPerformed

    private void OrderUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderUpdateActionPerformed
        // TODO add your handling code here:
        int i = OrderTable.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel)OrderTable.getModel();
        if (i >=0)
        {
            model.setValueAt(OrderID.getText(),i,0);
            model.setValueAt(OrderEmail.getText(),i,1);
            model.setValueAt(OrderQuantity.getText(),i,2);
            model.setValueAt(OrderStatus.getSelectedItem(), i, 3);
            
            OrderID.setText("");
            OrderEmail.setText("");
            OrderQuantity.setText("");
            OrderStatus.setSelectedIndex(0);
        }else{
            JOptionPane.showMessageDialog(null,"Error");
        }
        
    }//GEN-LAST:event_OrderUpdateActionPerformed

    private void ProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductIDActionPerformed

    private void FirstNameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameUserActionPerformed

    private void UserSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSaveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)UserTable.getModel();
        model.addRow(new Object[]{FirstNameUser.getText(),LastNameUser.getText(),EmailUser.getText(),PhoneUser.getText(),AddressUser.getText()});
        FirstNameUser.setText("");
        LastNameUser.setText("");
        EmailUser.setText("");
        PhoneUser.setText("");
        AddressUser.setText("");
        
    }//GEN-LAST:event_UserSaveActionPerformed

    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)ProductTable.getModel();
        int selectedRowIndex = ProductTable.getSelectedRow();
        
        ProductID.setText(model.getValueAt(selectedRowIndex,0).toString());
        ProductName.setText(model.getValueAt(selectedRowIndex,1).toString());
        ProductPrice.setText(model.getValueAt(selectedRowIndex,2).toString());
        ProductQuantity.setText(model.getValueAt(selectedRowIndex,3).toString());
        ProductCategory.setSelectedItem(model.getValueAt(selectedRowIndex,4));
        
                
    }//GEN-LAST:event_ProductTableMouseClicked

    private void PMupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMupdateActionPerformed
        // TODO add your handling code here:
        int i = ProductTable.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel)ProductTable.getModel();
        if (i >=0)
        {
            model.setValueAt(ProductID.getText(),i,0);
            model.setValueAt(ProductName.getText(),i,1);
            model.setValueAt(ProductPrice.getText(),i,2);
            model.setValueAt(ProductQuantity.getText(),i,3);
            model.setValueAt(ProductCategory.getSelectedItem(), i, 4);
            
            ProductID.setText("");
            ProductName.setText("");
            ProductPrice.setText("");
            ProductQuantity.setText("");
            ProductCategory.setSelectedIndex(0);
        }else{
            JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_PMupdateActionPerformed

    private void UserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserUpdateActionPerformed
        // TODO add your handling code here:
        int i = UserTable.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel)UserTable.getModel();
        if (i >=0)
        {
            model.setValueAt(FirstNameUser.getText(),i,0);
            model.setValueAt(LastNameUser.getText(),i,1);
            model.setValueAt(EmailUser.getText(),i,2);
            model.setValueAt(PhoneUser.getText(),i,3);
            model.setValueAt(AddressUser.getText(), i, 4);
            
            FirstNameUser.setText("");
            LastNameUser.setText("");
            EmailUser.setText("");
            PhoneUser.setText("");
            AddressUser.setText("");
        }else{
            JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_UserUpdateActionPerformed

    private void UserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)UserTable.getModel();
        int selectedRowIndex = UserTable.getSelectedRow();
        
        FirstNameUser.setText(model.getValueAt(selectedRowIndex,0).toString());
        LastNameUser.setText(model.getValueAt(selectedRowIndex,1).toString());
        EmailUser.setText(model.getValueAt(selectedRowIndex,2).toString());
        PhoneUser.setText(model.getValueAt(selectedRowIndex,3).toString());
        AddressUser.setText(model.getValueAt(selectedRowIndex,4).toString());
        
    }//GEN-LAST:event_UserTableMouseClicked

    private void OrderSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderSaveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)OrderTable.getModel();
        model.addRow(new Object[]{OrderID.getText(),OrderEmail.getText(),OrderQuantity.getText(),OrderStatus.getSelectedItem()});
        OrderID.setText("");
        OrderEmail.setText("");
        OrderQuantity.setText("");
        OrderStatus.setSelectedIndex(0);
        
    }//GEN-LAST:event_OrderSaveActionPerformed

    private void OrderDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)OrderTable.getModel();
        
        try {
            int SelectedRowIndex = OrderTable.getSelectedRow();
            if (SelectedRowIndex >= 0) {
                model.removeRow(SelectedRowIndex);
        
            OrderID.setText("");
            OrderEmail.setText("");
            OrderQuantity.setText("");
            OrderStatus.setSelectedIndex(0);
        
        } else {
            JOptionPane.showMessageDialog(null, "Please select an order to delete");
        }
        } catch(Exception ex) {
        JOptionPane.showMessageDialog(null, "Error deleting order: " + ex.getMessage());
        }
    }//GEN-LAST:event_OrderDeleteActionPerformed

    private void OrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)OrderTable.getModel();
        int selectedRowIndex = OrderTable.getSelectedRow();
        
        OrderID.setText(model.getValueAt(selectedRowIndex,0).toString());
        OrderEmail.setText(model.getValueAt(selectedRowIndex,1).toString());
        OrderQuantity.setText(model.getValueAt(selectedRowIndex,2).toString());
        OrderStatus.setSelectedItem(model.getValueAt(selectedRowIndex,3));
        
    }//GEN-LAST:event_OrderTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressUser;
    private javax.swing.JTextField EmailUser;
    private javax.swing.JTextField FirstNameUser;
    private javax.swing.JTextField LastNameUser;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JPanel ManageOrder;
    private javax.swing.JButton ManageOrderButton;
    private javax.swing.JButton MenuButton;
    private javax.swing.JButton OrderDelete;
    private javax.swing.JTextField OrderEmail;
    private javax.swing.JTextField OrderID;
    private javax.swing.JTextField OrderQuantity;
    private javax.swing.JButton OrderSave;
    private javax.swing.JComboBox<String> OrderStatus;
    private javax.swing.JTable OrderTable;
    private javax.swing.JButton OrderUpdate;
    private javax.swing.JButton PMdelete;
    private javax.swing.JButton PMsave;
    private javax.swing.JButton PMupdate;
    private javax.swing.JTextField PhoneUser;
    private javax.swing.JComboBox<String> ProductCategory;
    private javax.swing.JLabel ProductCategoryTxt;
    private javax.swing.JTextField ProductID;
    private javax.swing.JLabel ProductIDtxt;
    private javax.swing.JPanel ProductManagement;
    private javax.swing.JButton ProductManagementButton;
    private javax.swing.JTextField ProductName;
    private javax.swing.JLabel ProductNameTxt;
    private javax.swing.JTextField ProductPrice;
    private javax.swing.JLabel ProductPriceTxt;
    private javax.swing.JTextField ProductQuantity;
    private javax.swing.JLabel ProductQuantityTxt;
    private javax.swing.JTable ProductTable;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton UserDelete;
    private javax.swing.JPanel UserManagement;
    private javax.swing.JButton UserManagementButton;
    private javax.swing.JButton UserSave;
    private javax.swing.JTable UserTable;
    private javax.swing.JButton UserUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
